/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_basededonnee;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.text.AttributedString;
import java.util.ArrayList;
import java.util.List;

import javax.swing.AbstractAction;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.Timer;

import interface_basededonnee.API_YahooFinance;
import interface_basededonnee.Gestion_base_de_donnee;
import interface_basededonnee.ModeleDynamiqueObjet;
import interface_basededonnee.Portefeuille;
import interface_basededonnee.historique;

/**
 *
 * @author Utilisateur
 */
public class Panel_interface extends javax.swing.JPanel {

	private static ModeleDynamiqueObjet modele = new ModeleDynamiqueObjet();
	private static historique historique = new historique();
	static int nb_actions;
	static Timer timer_refresh; 
	
	public Panel_interface() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		ScrollPane_tableau = new javax.swing.JScrollPane();
		tableau = new javax.swing.JTable(modele);
		jLabel1 = new javax.swing.JLabel();
		ScrollPane_historique = new javax.swing.JScrollPane();
		liste_historique = new javax.swing.JList();
		label_total_portefeuille = new javax.swing.JLabel();
		bouton_ajouter = new javax.swing.JButton(new bouton_ajouter());
		bouton_supprimer = new javax.swing.JButton(new bouton_supprimer());
		bouton_rafraichir = new javax.swing.JButton(new bouton_rafraichir());
		jLabel2 = new javax.swing.JLabel();
		Champ_achat_vente = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		bouton_acheter = new javax.swing.JButton(new bouton_acheter());
		bouton_vendre = new javax.swing.JButton(new bouton_vendre());
		jLabel4 = new javax.swing.JLabel();
		Liste_choix_entreprises = new javax.swing.JComboBox();
		Liste_choix_ID = new javax.swing.JComboBox();
		choix_entreprise = new javax.swing.JLabel();
		Panelbas = new javax.swing.JPanel();


		ScrollPane_tableau.setViewportView(tableau);

		tableau.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				
				if (e.getClickCount()%1==0){
					//Liste_choix_entreprises.set
					}
				// s'il s'agit bien d'un double clic
				if (e.getClickCount()%2 == 0) {
					int ligne = tableau.getSelectedRow();
					String  cellule = tableau.getValueAt(ligne,1).toString(); 
					Interface_JavaFX_Swing.loadURL("https://fr.finance.yahoo.com/q?s="+ cellule);
				}


			}
		});

		jLabel1.setText("User : Alice");

		liste_historique.setModel(historique);
		ScrollPane_historique.setViewportView(liste_historique);

		bouton_ajouter.setText("Ajouter une entreprise");

		
		/*bouton_ajouter.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {


				ArrayList<String> listeIDcorrespondant = Gestion_base_de_donnee.recupererlisteID();
				String IDcorrespondant = null;
				JComboBox jcb = new JComboBox(listeentreprises1.toArray());
				//jcb.setEditable(true);
				JOptionPane.showMessageDialog( null, jcb, "select or type a value", JOptionPane.QUESTION_MESSAGE);
				Object entreprise_a_ajouter = jcb.getSelectedItem();
				String entreprise_a_ajouter_string = entreprise_a_ajouter.toString();  
				// recuperer l'ID correspondant

				for( int i=0;i<listeIDcorrespondant.size();i++){
					if(i==listeentreprises1.indexOf(entreprise_a_ajouter)){
						IDcorrespondant = listeIDcorrespondant.get(i);
						//listeIDcorrespondant.remove(i);
					}
				}



				nombre_actions_entreprise_a_ajouter = (String)JOptionPane.showInputDialog(Panel_interface.bouton_ajouter, "Combien d'actions possedez vous dans cette entreprise ?",  "Nombre d'actions", JOptionPane.QUESTION_MESSAGE);
				nb_actions= Integer.parseInt(nombre_actions_entreprise_a_ajouter);
				Double total1= null;

				try {
					total1 =Portefeuille.floor( nb_actions*(API_YahooFinance.valeuraction(IDcorrespondant)),3);
				} catch (IOException e2) {
					// TODO Auto-generated catch block
					e2.printStackTrace();
				}

				try {  			
					modele.addLigne(new Portefeuille(entreprise_a_ajouter_string, IDcorrespondant ,nb_actions  ,API_YahooFinance.valeuraction(IDcorrespondant)+" "+ "euros".toString(),total1.toString()+" "+"euros"));
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}	
				try {

					Gestion_base_de_donnee.sauverlignedansBase(entreprise_a_ajouter_string,IDcorrespondant,nb_actions,API_YahooFinance.valeuraction(IDcorrespondant),total1);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}	

				Gestion_base_de_donnee.remplir_Jcombobox();
				for( int i=0;i<listeIDcorrespondant.size();i++){
					if(entreprise_a_ajouter==listeIDcorrespondant.get(i)){
						listeIDcorrespondant.remove(i);
					}
				}
				totalportefeuille = Gestion_base_de_donnee.calcultotalportefeuille();
				totalportefeuilleaffiche=Portefeuille.floor(totalportefeuille,3);
				// On retire l'ID et le nom de la liste pour garder la correspondance et ne plus les avoir dans laJcomboBox


				for( int i=0;i<listeIDcorrespondant.size();i++){
					if(i==listeentreprises1.indexOf(entreprise_a_ajouter)){
						listeIDcorrespondant.remove(i);
					}
				} for( int i=0;i<listeentreprises1.size();i++){
					if(i==listeentreprises1.indexOf(entreprise_a_ajouter)){
						listeentreprises1.remove(i);

					}
				}


				timer_refresh = Timer_rafraichissement.createTimer();
				timer_refresh.start();

				label_total_portefeuille.setText("Total du portefeuille : "+ totalportefeuilleaffiche  + " euros");
			} 
		});*/



		bouton_supprimer.setText("Supprimer les lignes selectionnees");
		bouton_rafraichir.setText("Rafraichir");
		jLabel2.setText("        Achat / Vente d'actions");
		Champ_achat_vente.setText("");
		jLabel3.setText("Quantité : ");
		bouton_acheter.setText("Acheter");
		bouton_vendre.setText("Vendre");
		jLabel4.setText("Résumé :");
		choix_entreprise.setText("Entreprise :");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(234, 234, 234)
										.addComponent(bouton_ajouter)
										.addGap(41, 41, 41)
										.addComponent(bouton_supprimer))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(189,189,189)
														.addComponent(label_total_portefeuille, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(256, 256, 256)
														.addComponent(bouton_rafraichir))
												.addComponent(ScrollPane_tableau, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																		.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(8, 8, 8))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(jLabel3)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(Champ_achat_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(choix_entreprise)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(Liste_choix_entreprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGap(34, 34, 34)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(bouton_acheter)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(bouton_vendre))
																.addComponent(ScrollPane_historique, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(bouton_rafraichir)
								.addComponent(jLabel2)
								.addComponent(label_total_portefeuille))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(ScrollPane_tableau, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Liste_choix_entreprises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(choix_entreprise))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(Champ_achat_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(bouton_vendre)
												.addComponent(bouton_acheter))
										.addGap(12, 12, 12)
										.addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(ScrollPane_historique, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(bouton_ajouter)
								.addComponent(bouton_supprimer))
						.addGap(12, 12, 12))
				);

		

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(Panelbas, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(58, Short.MAX_VALUE))
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(Panelbas, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
						.addContainerGap())
				);
	}// </editor-fold>                                                                                                                                                                      


	// Variables declaration - do not modify                     
	static javax.swing.JTextField Champ_achat_vente;
	static javax.swing.JComboBox Liste_choix_entreprises;
	static javax.swing.JComboBox Liste_choix_ID;
	static javax.swing.JPanel Panelbas;
	private javax.swing.JScrollPane ScrollPane_historique;
	private javax.swing.JScrollPane ScrollPane_tableau;
	private javax.swing.JButton bouton_acheter;
	static javax.swing.JButton bouton_ajouter;
	static  javax.swing.JButton bouton_rafraichir;
	static  javax.swing.JButton bouton_supprimer;
	static  javax.swing.JButton bouton_vendre;
	private javax.swing.JLabel choix_entreprise;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	static javax.swing.JLabel label_total_portefeuille;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JProgressBar jProgressBar1;
	static javax.swing.JTable tableau;

	private javax.swing.JList liste_historique;
/*
	static String nom_entreprise_ajouter;
	static String nombre_actions_entreprise_a_ajouter;
	static Double total;
	static double totalportefeuille;
	static double totalportefeuilleaffiche;
	static ArrayList<String> listeentreprises1;
	static ArrayList<String> listeentreprises2;
	static ArrayList<String> listeentreprise = Gestion_base_de_donnee.recupererlisteentrepriseajouter();*/
	// End of variables declaration                   
}
